### ISSUE TITLE
immediate crash on launch

### ISSUE THREAD

**Issue by Der-Flip** [ThiBsc/UnitsTool#5]
As title describes, I don't have many info on it.

have the app installed for quite some time, now. Wanted to launch it recently but it crashed immediately on launch.
After deleting cache and all app data as well as a re-install app still crashes immediately

attached is the catlog (logcat?), hopefully done correctly.
[2022-09-08-17-49-53_unittool.txt](https://github.com/ThiBsc/UnitsTool/files/9528464/2022-09-08-17-49-53_unittool.txt)

Redmi 9C
MIUI Global 12.0.14 stable (As well as previous release)
Android 10 QP1A.190711.020
Security Updates: 22-07-01

**Comment by ThiBsc** [comment]
Hi, thank you for using the application.

Can you tell me on which store do you installed it (Google or F-Droid), and also the version of the application (I guess 1.0.6?).

I'll take a look to it when I'll find time, but thank you for helping me improve the application.

**Comment by Der-Flip** [comment]
Hi, my apologies, I knew I forgot something
App Version 1.0.6 via fdroid (droidify)
https://www.f-droid.org/packages/com.unitstool/

**Comment by ThiBsc** [comment]
Could you just test to use the version of the Play store to know if the problem can come from the generated apk itself or not ?

**Comment by Der-Flip** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Absolutely!The PlayStore app seems to work.I tried reinstalling the fdroid version after testing the PlayStore and that was crashing again.                                                                                                                                                                                                                                                                                                                        Von: ***@***.***: 8. September 2022 8:25 PMAn: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [ThiBsc/UnitsTool] immediate crash on launch (Issue #5)  
Could you just test to use the version of the Play store to know if the problem can come from the generated apk itself or not ?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ThiBsc** [comment]
Ok, so the problem should come more from the apk on F-Droid than from the application itself, it's nice to know.

**Comment by ThiBsc** [comment]
You're right, I tested with the last version of the app on the F-Droid store and I have the same problem. But not with the 1.0.5 version, it seems to be the generating process on F-Droid that provide a bad APK for this store. So by waiting I'm investigate more. You can use the 1.0.6 version of the play store or the 1.0.5 version of the F-Droid store

**Comment by ThiBsc** [comment]
The problem seems to be after an update that I made, to solve it, I run this command before generate my apk:
`npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle` like it said on this [issue](https://github.com/react-native-community/upgrade-support/issues/38), so I have to update the yml file on the f-droid side. I will find time, except if you want to do it, but this line seems to solve the APK generated.
The generated apk was asking for Metro server like if I was in debug bug, I don't know really why, but it was the cause

**Comment by ThiBsc** [comment]
@Der-Flip I fixed the apk of the F-Droid store for the `v1.0.6`, can you confirm it's now working ? As I can close this issue

**Comment by Der-Flip** [comment]
hi sorry, didn't have time before and didn't realize you pushed it already to f-droid as it still shows 4th August as 1.0.6's publishing date.
Tested it and it does indeed start up now.
Thanks! :)

**Comment by ThiBsc** [comment]
Yes, the date hasn't change because the problem was in the apk generation process, not in the source code. So F-Droid display the same date
